@baseUrl = http://127.0.0.1:8080/api

### Create User
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "userId": "91486ee9-e4e2-47c3-b9a6-61e72f7845d1"
}

### Find account by Id
GET {{baseUrl}}/accounts/293cf95c-3654-45b0-b9d8-291328f69db7


### Delete account by Id
DELETE {{baseUrl}}/accounts/293cf95c-3654-45b0-b9d8-291328f69db7

